proyecto/MisCosasApp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('informacion/', views.informacion, name='informacion'),
    path('usuarios/', views.usuarios, name='usuarios'),
    path('alimentadores/', views.alimentadores, name='alimentadores'),
    path('registro/', views.registro, name='registro'),
    path('usr_logout/', views.usr_logout, name='usr_logout'),
    path('error404/', views.error_404, name='error_404'),
    path('<str:llave1>/<str:llave2>', views.proceso_alimentador, name= 'proceso_alimentador'),
    path('<str:llave>/<str:llave1>/Deseleccionar', views.borrar_alimentador, name= 'borrar_alimentador'),
    path('<str:llave>/<str:llave1>/<str:llave2>', views.proceso_item, name= 'proceso_item'),
    path('usuario/<str:llave>',views.usuario, name='usuario'),
    path('<str:llave>/<str:llave1>/<str:llave2>/<str:llave3>/votopositivo/', views.votos, name='votos'),
    path('<str:llave>/<str:llave1>/<str:llave2>/<str:llave3>/votonegativo/', views.votos, name='votos'),
]

proyecto/proyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('miscosas/', include('MisCosasApp.urls'))
]+ static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)

proyecto/MisCosasApp/models.py
from django.db import models
from django.utils import timezone

class Users(models.Model):
    username = models.CharField(max_length=64, default="")
    email = models.EmailField(max_length=64, default="")
    password = models.CharField(max_length=64, default="")

    def __str__(self):
        return self.username + " " + self.email + " " + self.password

class Alimentador(models.Model):
    alimentadorId = models.CharField(max_length=64, default="")
    nombre = models.CharField(max_length=64, default="")
    enlace = models.CharField(max_length=64, default="")
    puntuacion = models.IntegerField(default=0)
    type = models.CharField(max_length=64,default="")
    pagPrincipal = models.BooleanField(default=True)

    def __str__(self):
        return self.nombre


class Item(models.Model):
    nombre = models.CharField(max_length=64, default="")
    enlace = models.CharField(max_length=64, default="yo ")
    itemId = models.CharField(max_length=64, default="")
    fotoItem = models.CharField(max_length=64, default="")
    descripcion = models.TextField(blank=False, default="")
    votosPositivos = models.IntegerField(default=0)
    votosNegativos = models.IntegerField(default=0)
    votosTotales = models.IntegerField(default=0)
    alimentador = models.ForeignKey(Alimentador, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre

class Comentario(models.Model):
    usuario = models.ForeignKey(Users, on_delete=models.CASCADE)
    fecha = models.DateTimeField(default=timezone.now)
    texto = models.TextField(blank=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='Comments', null=True, default="")


class Voto(models.Model):
    usuario = models.ForeignKey(Users, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    estado = models.CharField(max_length=64, default="")

proyecto/MisCosasApp/forms.py
from django import forms

class FormularioRegistro(forms.Form):
    Usuario= forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Introduzca un usuario'}))
    Email= forms.EmailField(widget=forms.TextInput(attrs={
        'placeholder': 'Introduzca su email'}))
    Contraseña= forms.CharField(max_length=32, widget=forms.PasswordInput)


class FormularioLogin(forms.Form):
    Usuario= forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Introduzca su usuario'}))
    Contraseña= forms.CharField(max_length=32, widget=forms.PasswordInput)

proyecto/MisCosasApp/views.py
import sys

from django.shortcuts import render, redirect
from .forms import FormularioRegistro, FormularioLogin
from .models import Users, Alimentador, Item, Voto, Comentario
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponseForbidden
import urllib.request
from xml.sax import make_parser
from .parseyt import YTHandler
from .apikeys import LASTFM_APIKEY
from .parselastfm import LastfmHandler
from unidecode import unidecode


def index(request): # CREO QUE ESTÁ TERMINADO, NO ESTOY SEGURO
    paginaPrincipal = True
    form = FormularioLogin()
    context = {'form': form}
    if request.method == "POST":
        form = FormularioLogin(request.POST, request.FILES)
        if form.is_valid():
            nombre = form.cleaned_data['Usuario']
            contraseña = form.cleaned_data['Contraseña']
            user = authenticate(request, username=nombre, password=contraseña)
            if user is not None:
                login(request, user)
                return redirect("index")
            else:
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    if request.method == "POST":
        action = request.POST.get('action',False)
        if action == "youtube":
            idchannel = request.POST['idyoutube']
            redireccion = "/miscosas/youtube/" + idchannel
            return HttpResponseRedirect(redireccion)

        elif action == "lastfm":
            artist = request.POST['artistlast']
            artist = unidecode(artist)
            redireccion = "/miscosas/lastfm/" + artist
            return HttpResponseRedirect(redireccion)

    alimentadoresYT = Alimentador.objects.filter(pagPrincipal=True, type="youtube")
    alimentadoresLF = Alimentador.objects.filter(pagPrincipal=True, type="lastfm")

    items =Item.objects.all()
    for item in items:
        item.votosTotales = item.votosPositivos - item.votosNegativos
        item.save()

    itemsOrdenados = Item.objects.all().order_by('-votosTotales')[:10]

    context = {'paginaPrincipal': paginaPrincipal,
               'form': form,
               'alimentadoresYT': alimentadoresYT,
               'alimentadoresLF': alimentadoresLF,
               'top10': itemsOrdenados}

    user = request.user.username
    if user:
        try:
            user = Users.objects.get(username=user)
        except Users.DoesNotExist:
            user = Users(username=user)
            user.save()
        votos = Voto.objects.filter(usuario=user).order_by('-id')[:5]
        context['itemsvotados'] = votos

    return render(request, 'MisCosasApp/index.html', context)

def informacion(request): # TERMINADO
    return render(request, 'MisCosasApp/informacion.html')

def usuarios(request): # TERMINADO
    users = Users.objects.all()
    context = {'users': users}

    return render(request,'MisCosasApp/usuarios.html', context)


def alimentadores(request): # TERMINADO
    try:
        alimentadoresYT = Alimentador.objects.filter(type="youtube")
        alimentadoresLF = Alimentador.objects.filter(type="lastfm")

        context = {'alimentadoryoutube': alimentadoresYT,
                   'alimentadoreslast': alimentadoresLF}

    except Alimentador.DoesNotExist:
        context = {}
    return render(request, 'MisCosasApp/alimentadores.html',context)

def registro(request): # TERMINADO
    form = FormularioRegistro()
    context = {'form': form}
    if request.method == "POST":
        form = FormularioRegistro(request.POST, request.FILES)
        if form.is_valid():
            nombre = form.cleaned_data['Usuario']
            email = form.cleaned_data['Email']
            contraseña = form.cleaned_data['Contraseña']
            try:
                superUser = User.objects.get(username=nombre)
                context['error'] = 'Usuario existente, pruebe otro'
                return render(request, 'MisCosasApp/registro.html', context)
            except User.DoesNotExist:
                try:
                    user = Users.objects.get(username=nombre)
                    context['error'] = 'Usuario existente, pruebe otro'
                    return render(request, 'MisCosasApp/registro.html', context)
                except Users.DoesNotExist:
                    u = Users(username=nombre, email=email, password=contraseña)
                    u.save()
                    user = User.objects.create_user(username=nombre, email=email, password=contraseña)
                    user.save()
                    if user is not None:
                        login(request, user)
                    return render(request, 'MisCosasApp/index.html', context)

    return render(request, 'MisCosasApp/registro.html', context)

def usr_logout(request): #TERMINADO
    logout(request)
    return redirect(index)

def error_404(request): # TERMINADO
    return render(request, 'MisCosasApp/error404.html')

def proceso_alimentador(request, llave1, llave2): # TERMINADO
    Parser = make_parser()
    if llave1 == 'youtube':
        Parser.setContentHandler(YTHandler())
        url = 'https://www.youtube.com/feeds/videos.xml?channel_id=' \
            + llave2
    if llave1 == 'lastfm':
        llavetraducida = llave2.replace(" ", "%20")
        Parser.setContentHandler(LastfmHandler())
        url = 'http://ws.audioscrobbler.com/2.0/?method=artist.gettopalbums&artist=' + llavetraducida + '&api_key=' + LASTFM_APIKEY
    try:
        xmlStream = urllib.request.urlopen(url)
        Parser.parse(xmlStream)
    except:
        return render(request, 'MisCosasApp/error404.html', {})
    try:
        a = Alimentador.objects.get(alimentadorId=llave2)
    except:
        return render(request, 'MisCosasApp/error404.html', {})

    items = Item.objects.filter(alimentador=a)

    for item in items:
        item.votosTotales = item.votosPositivos - item.votosNegativos
        item.save()

    context = {'contentList': items,
               'alimentador': a}

    return render(request, 'MisCosasApp/alimentador.html', context)

def proceso_item(request, llave, llave1, llave2): # TERMINADO
    a = Alimentador.objects.get(alimentadorId=llave1)
    i = Item.objects.get(itemId=llave2)

    context = {'alimentador': a,
               'item': i}

    return render(request, 'MisCosasApp/item.html', context)

def borrar_alimentador(llave, llave1): # ERROR!!!!!!!!!!!!!!!!!

    a = Alimentador.objects.get(type=llave, alimentadorId=llave1)
    a.pagPrincipal = not a.pagPrincipal
    a.save()

    return redirect('index')

def usuario(request, llave):
    users = Users.objects.get(username=llave)
    itemsComentados = Comentario.objects.filter(usuario=users)
    itemsVotados = Voto.objects.filter(usuario=users)
    context = {'users': users,
               'itemscomentados': itemsComentados,
               'itemsvotados': itemsVotados,
               }

    if users.username == request.user.username:
        sameuser = True
        context['sameuser'] = sameuser

    return render(request, 'MisCosasApp/usuario.html', context)

def votos(request, llave, llave1, llave2, llave3):
    i = Item.objects.get(itemId=llave2)
    name = request.user.username
    if name:
        action = request.POST.get('action', None)
        u = Users.objects.get(username=name)

        if action == "votopositivo":
            try:
                v = Voto.objects.get(usuario=u, item=i)
                if v.estado == "estadonegativo":
                    i.votosPositivos = i.votosPositivos + 1
                    i.votosNegativos = i.votosNegativos - 1
                    i.save()
                v.estado = "estadopositivo"
                v.save()
            except Voto.DoesNotExist:
                i.votosPositivos = i.votosPositivos + 1
                i.save()
                v = Voto(usuario=u, item=i, estado="estadopositivo")
                v.save()

        elif action == "votonegativo":
            try:
                v = Voto.objects.get(usuario=u, item=i)
                if v.estado == "estadopositivo":
                    i.votosPositivos = i.votosPositivos - 1
                    i.votosNegativos = i.votosNegativos + 1
                    i.save()
                v.estado = "estadonegativo"
                v.save()
            except Voto.DoesNotExist:
                i.votosNegativos = i.votosNegativos + 1
                i.save()
                v = Voto(usuario=u, item=i, estado="estadonegativo")
                v.save()

            a = Alimentador.objects.get(alimentadorId=llave1)
            items = Item.objects.filter(alimentador=a)
            votospos = 0
            votosne = 0
            for votos in items:
                votospos = votos.votosPositivos + votospos
                votosne = votos.votosNegativos + votosne

            puntuacionAlimentador = votospos - votosne
            a.puntuacion = puntuacionAlimentador
            a.save()
        if llave3 == 'paginaPrincipal':
            redireccion = "/miscosas/"
        elif llave3 == 'paginaItem':
            redireccion = "/miscosas" + "/" + llave + "/" + llave1 + "/" + llave2

        return redirect(redireccion)

proyecto/MisCosasApp/templates/MisCosasApp/alimentadores.html
{% extends 'MisCosasApp/base.html' %}
{% load static %}

{% block barra_nav %}

    <nav>
        <ul>
            <li><a href="/miscosas/" class="barra">Inicio</a></li> <!-- cambiar por un icono de una casa -->
            <li><a href="/miscosas/usuarios" class="barra">Usuarios</a></li>
            {% if user.is_authenticated %}
            <li style="float:right"><a href="/miscosas/usr_logout" class="barra">Cerrar sesión</a></li>
            {% endif %}
            <li style="float:right"><a href="/miscosas/informacion" class="barra">Información</a></li>
        </ul>
    </nav>

{% endblock %}

{% block contenido %}

<div class="cabeceras">
        <img src="{% static 'MisCosasApp/cabecera_alimentadores.png' %}">
</div>

<section id="alimentadores">
        <br><p class="texto_alimentadores">En esta sección se muestra una lista de los alimentadores que han sido visitados por algún usuario de la web, esté
        registrado o no. Podremos acceder a su contenido o eliminarlos si así lo deseamos:</p><br>
        <div class="flexbox-container">
            <div>
                <div>
                    <h2 class="alimentador_historial">Youtube</h2>
                </div>
                <div id="alimentadores_youtube">
                    {% for alimentadorYT in alimentadoryoutube %}
                    <h3 class="nombre_historial">
                        <a href="{{alimentadorYT.enlace}}">{{alimentadorYT.nombre}}</a><br>
                    </h3>
                    <div>
                        <h5>Ítems totales: {{alimentadorYT.item_set.count}}</h5>
                        <h5>Puntuación total: {{alimentadorYT.puntuacion}}</h5>
                        <form action="/miscosas/{{alimentadorYT.type}}/{{alimentadorYT.alimentadorId}}" method="POST">
                        {% csrf_token %}
                            <button type="submit" class="boton_historial">Volver al alimentador</button>
                        </form><br>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div>
                <div>
                    <h2 class="alimentador_historial">Last.fm</h2>
                </div>
                <div id="alimentadores_lastfm">
                    {% for alimentadorLF in alimentadoreslast %}
                    <h3 class="nombre_historial">
                        <a href="{{alimentadorLF.enlace}}">{{alimentadorLF.nombre}}</a><br>
                    </h3>
                    <div>
                        <h5>Ítems totales: {{alimentadorLF.item_set.count}}</h5>
                        <h5>Puntuación total: {{alimentadorLF.puntuacion}}</h5>
                        <form action="/miscosas/{{alimentadorLF.type}}/{{alimentadorLF.alimentadorId}}" method="POST">
                        {% csrf_token %}
                            <button type="submit" class="boton_historial">Volver al alimentador</button>
                        </form><br>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>

{% endblock %}

proyecto/MisCosasApp/templates/MisCosasApp/index.html
{% extends 'MisCosasApp/base.html' %}
{% load static %}

{% block barra_nav %}

<nav>
    <ul>
        <li><a href="/miscosas/alimentadores" class="barra">Alimentadores</a></li>
        <li><a href="/miscosas/usuarios" class="barra">Usuarios</a></li>
        {% if user.is_authenticated %}
        <li style="float:right"><a href="/miscosas/usr_logout" class="barra">Cerrar sesión</a></li>
        {% endif %}
        <li style="float:right"><a href="/miscosas/informacion" class="barra">Información</a></li>
    </ul>
</nav>

{% endblock %}

{% block contenido %}

<div class="cabeceras">
    <img src="{% static 'MisCosasApp/cabecera_index.png' %}">
</div>

{% if user.is_authenticated %}
<section class="top10">
    <h1 class="bienvenida">BIENVENID@ {{user.username}}</h1><br>
    <h1 class="titulos_index">TOP 10 items</h1>
    <hr>
    <div>
        {% for item in top10 %}
        <h3>
            <a href="{{item.enlace}}">{{item.nombre}}</a><br>
        </h3>
        <div>
            <h5>Votos positivos: {{item.votosPositivos}}</h5>
            <h5>Votos negativos: {{item.votosNegativos}}</h5>
        </div>
        <form action="/miscosas/youtube/{{item.alimentador.alimentadorId}}/{{item.itemId}}" method="POST">
            {% csrf_token %}
            <button type="submit" class="boton_historial">Volver al alimentador</button>
        </form><br>
        {% endfor%}
    </div>
</section>

<section class="top10">
    <div>
        <h1 class="titulos_index">Últimos ítems votados por ti</h1>
        <hr>
        <div>
        {% for voto in itemsvotados %}
        <h3>
            <a href="{{voto.item.enlace}}">{{voto.item.nombre}}</a>
        </h3><br>
        </div>
                        <form action="{{alimentadores.type}}/{{alimentadores.alimentadorId}}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="boton_historial">Volver al item</button>
                </form><br>
        {% endfor %}
    </div>

</section>

<section class="alimentadores_user">
    <div class="alimentadores_index">
        <h1 class="titulos_index">ALIMENTADORES</h1>
        <hr>
        <p>Rellena los campos para obtener información sobre el alimentador que desees:</p><br>
        <div class="flexbox-container">
            <div>
                <a href="https://www.youtube.com" class="enlace_yt"><img src="{% static 'MisCosasApp/yt_index.png' %}"></a>
                <form class="formulario_index_yt" method="POST" action="/miscosas/">
                {% csrf_token %}
                <div class="yt_index">
                    <input class="yt_input" type="text" placeholder="Id del canal" name="idyoutube" id="youtube_registro">
                </div>
                    <button type="submit" class="boton_index_yt" name="action" value="youtube">Buscar</button>
                </form><br><br>
            </div>
            <div>
                <a href="https://www.last.fm" class="enlace_lastfm"><img src="{% static 'MisCosasApp/lastfm_index.png' %}"></a>
                <form class="formulario_index_lastfm" method="POST" action="/miscosas/">
                {% csrf_token %}
                <div class="lastfm_index">
                    <input class="lastfm_input" placeholder="Nombre del artista"  name="artistlast" id="lastfm_registro">
                </div>
                    <button type="submit" class="boton_index_lastfm" name="action" value="lastfm">Buscar</button>
                </form><br><br>
            </div>
        </div>
    </div>
</section>

<section id="historial_user">
    <h1>HISTORIAL ALIMENTADORES</h1>
    <hr>
    <p>En esta sección se muestra una lista de los alimentadores que han sido visitados por algún usuario de la web, esté
        registrado o no. Podremos acceder a su contenido o eliminarlos si así lo deseamos:</p><br>
    <div class="flexbox-container">
        <div>
            <div>
                <h2 class="alimentador_historial">Youtube</h2>
            </div>
            <div id="historial_youtube_user">
            {% for alimentadores in alimentadoresYT %}
            <h3 class="nombre_historial">
                <a href="{{alimentadores.enlace}}">{{alimentadores.nombre}}</a>
            </h3>
            <div>
                <h5>Ítems totales: {{alimentadores.item_set.count}}</h5>
                <h5>Puntuación total: {{alimentadores.puntuacion}}</h5>
                <form action="{{alimentadores.type}}/{{alimentadores.alimentadorId}}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="boton_historial">Volver al alimentador</button>
                </form><br>
                <form action="{{alimentadores.type}}/{{alimentadores.alimentadorId}}/paginaPrincipal/Deseleccionar" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="boton_historial">Eliminar</button>
                </form>
            </div>
            {% endfor %}
            </div>
        </div>
        <div>
            <div>
                <h2 class="alimentador_historial">Last.fm</h2>
            </div>
            <div id="historial_lastfm_user">
            {%for alimentadores in alimentadoresLF%}
            <h3 class="nombre_historial">
                <a href="{{alimentadores.enlace}}">{{alimentadores.nombre}}</a>
            </h3>
            <div>
                <h5>Ítems totales: {{alimentadores.item_set.count}}</h5>
                <h5>Puntuación total: {{alimentadores.puntuacion}}</h5>
                <form action="{{alimentadores.type}}/{{alimentadores.alimentadorId}}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="boton_historial">Volver al alimentador</button>
                </form><br>
                <form action="{{alimentadores.type}}/{{alimentadores.alimentadorId}}/Deseleccionar" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="boton_historial">Eliminar</button>
                </form><br>
            </div>
            {% endfor %}
            </div>
        </div>
    </div>
</section>

{% else %} <!-- DESDE AQUÍ SI NO ESTÁS LOGEADO -->
<div class="formulario_index">
    <form action="/miscosas/" method="POST" name="formulario_index"><br>
        {% csrf_token %}
        {{form.as_p}}
            <button type="submit" class="boton_index" >Entrar</button>
            <p><a href="/miscosas/registro">Regístrate rápidamente</a></p>
    </form>
    </div>
        {%if error%}
        <p>{{error}}</p>
        {%endif%}
</div>

<section class="top10">
    <h1 class="titulos_index">TOP 10 items</h1>
    <hr><br>
    <div>
        {% for item in top10 %}
        <h3>
            <a href="{{item.enlace}}">{{item.nombre}}</a><br>
        </h3>
        <div>
            <h5>Votos positivos: {{item.votosPositivos}}</h5>
            <h5>Votos negativos: {{item.votosNegativos}}</h5>
        </div>
        <form action="/miscosas/youtube/{{item.alimentador.alimentadorId}}/{{item.itemId}}" method="POST">
            {% csrf_token %}
            <button type="submit" class="boton_historial">Volver al alimentador</button>
        </form><br>
        {% endfor%}
    </div>
</section>

<section class="alimentadores_user">
    <div class="alimentadores_index">
        <h1 class="titulos_index">ALIMENTADORES</h1>
        <hr>
        <p>Rellena los campos para obtener información sobre el alimentador que desees:</p><br>
        <div class="flexbox-container">
            <div>
                <a href="https://www.youtube.com" class="enlace_yt"><img src="{% static 'MisCosasApp/yt_index.png' %}"></a>
                <form class="formulario_index_yt" method="POST" action="/miscosas/">
                {% csrf_token %}
                <div class="yt_index">
                    <input class="yt_input" type="text" placeholder="Id del canal" name="idyoutube" id="youtube_registro">
                </div>
                    <button type="submit" class="boton_index_yt" name="action" value="youtube">Buscar</button>
                </form><br><br>
            </div>
            <div>
                <a href="https://www.last.fm" class="enlace_lastfm"><img src="{% static 'MisCosasApp/lastfm_index.png' %}"></a>
                <form class="formulario_index_lastfm" method="POST" action="/miscosas/">
                {% csrf_token %}
                <div class="lastfm_index">
                    <input class="lastfm_input" placeholder="Nombre del artista"  name="artistlast" id="lastfm_registro">
                </div>
                    <button type="submit" class="boton_index_lastfm" name="action" value="lastfm">Buscar</button>
                </form><br><br>
            </div>
        </div>
    </div>
</section>

<section id="historial">
    <h1 class="titulos_index">HISTORIAL ALIMENTADORES</h1>
    <hr>
    <p>En esta sección se muestra una lista de los alimentadores que han sido visitados por algún usuario de la web, esté
        registrado o no. Podremos acceder a su contenido o eliminarlos si así lo deseamos:</p><br>
    <div class="flexbox-container">
        <div>
            <div>
                <h2 class="alimentador_historial">Youtube</h2>
            </div>
            <div id="historial_youtube">
            {% for alimentadores in alimentadoresYT %}
            <h3 class="nombre_historial">
                <a href="{{alimentadores.enlace}}">{{alimentadores.nombre}}</a>
            </h3>
            <div>
                <h5>Ítems totales: {{alimentadores.item_set.count}}</h5>
                <h5>Puntuación total: {{alimentadores.puntuacion}}</h5>
                <form action="{{alimentadores.type}}/{{alimentadores.alimentadorId}}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="boton_historial">Volver al alimentador</button>
                </form><br>
                <form action="{{alimentadores.type}}/{{alimentadores.alimentadorId}}/paginaPrincipal/Deseleccionar" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="boton_historial">Eliminar</button>
                </form>
            </div>
            {% endfor %}
            </div>
        </div>
        <div>
            <div>
                <h2 class="alimentador_historial">Last.fm</h2>
            </div>
            <div id="historial_lastfm">
            {%for alimentadores in alimentadoresLF%}
            <h3 class="nombre_historial">
                <a href="{{alimentadores.enlace}}">{{alimentadores.nombre}}</a>
            </h3>
            <div>
                <h5>Ítems totales: {{alimentadores.item_set.count}}</h5>
                <h5>Puntuación total: {{alimentadores.puntuacion}}</h5>
                <form action="{{alimentadores.type}}/{{alimentadores.alimentadorId}}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="boton_historial">Volver al alimentador</button>
                </form><br>
                <form action="{{alimentadores.type}}/{{alimentadores.alimentadorId}}/Deseleccionar" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="boton_historial">Eliminar</button>
                </form><br>
            </div>
            {% endfor %}
            </div>
        </div>
    </div>
</section>



</div>

{% endif %} <!-- CIERRA EL ELSE DE LA LÍNEA 57 -->
{% endblock %}

proyecto/MisCosasApp/templates/MisCosasApp/usuarios.html
{% extends 'MisCosasApp/base.html' %}
{% load static %}

{% block barra_nav %}

    <nav>
        <ul>
            <li><a href="/miscosas/" class="barra">Inicio</a></li> <!-- cambiar por un icono de una casa -->
            <li><a href="/miscosas/alimentadores" class="barra">Alimentadores</a></li>
            {% if user.is_authenticated %}
            <li style="float:right"><a href="/miscosas/usr_logout" class="barra">Cerrar sesión</a></li>
            {% endif %}
            <li style="float:right"><a href="/miscosas/informacion" class="barra">Información</a></li>
        </ul>
    </nav>

{% endblock %}

{% block contenido %}
<div class="cabeceras">
        <img src="{% static 'MisCosasApp/cabecera_usuarios.png' %}">
</div>

<section class="">
    <div class="usuarios">
        {% for usuario in users %}
        <div>
            <p><a class="nombre_usuarios" href="/miscosas/usuario/{{usuario.username}}"></p><br>
        </div>
        <div>
            <img class="logo_usuarios" src="{% static 'MisCosasApp/logo_usuarios.png' %}"><br>{{usuario.username}}</a>
        </div><br>
        <p>Ítems votados: {{usuario.voto_set.count}}<br>
        Ítems comentados: {{usuario.comentario_set.count}}</p>
    </div>
    {% endfor %}
</section>
    <p></p>

{% endblock %}